- job: 
  tags:
    
    - "monitoring"
    
  project: "qubit-vcloud-eu-proc-prod"
  ports:
    
    - 80
    

- job: kafka
  tags:
    
    - "kafka-server"
    
  project: "qubit-vcloud-eu-proc-prod"
  ports:
    
    - 9100
    

- job: orca
  tags:
    
    - "orca-service-server"
    
  project: "qubit-vcloud-eu-proc-prod"
  ports:
    
    - 32336
